server:
  compression:
    enabled: true
  error.whitelabel.enabled: false
  port: 8082

logging:
  level:
    org.springframework.security: debug
    web: info

spring:
  application:
    name: training-session-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:trSession;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gymcrm
  h2:
    console:
      enabled: false
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true

eureka:
  client:
    restclient:
      enabled: on
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: on