server:
  compression:
    enabled: true
  error.whitelabel.enabled: false
  port: 8082

logging:
  level:
    org.springframework.security: debug
    web: info

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/gym-crm
  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin
    mode: native
  application:
    name: training-session-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gymcrm
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true

eureka:
  client:
    enabled: on
    restclient:
      enabled: on
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
