server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service
          uri: http://localhost:8081
          predicates:
            - path=/api/**
          filters:
            - strip-prefix=1
        - id: training-session-service
          uri: http://localhost:8082
          predicates:
            - path=/api/**
          filters:
            - strip-prefix=1
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://mock-issuer
          jwk-set-uri: http://mock-issuer/.well-known/jwks.json
