server:
  port: 8081

logging:
  level:
    root: INFO

eureka:
  client:
    restclient:
      enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: gym-service
              uri: lb://gym-service
              predicates:
                - Path=/gym/**
              filters:
                - stripPrefix=1
            - id: training-session-service
              uri: lb://training-session-service
              predicates:
                - Path=/tr_session/**
              filters:
                - stripPrefix=1
