server:
  port: 8083

logging:
  level:
    root: WARN
    web: INFO
    net.ttddyy.dsproxy.listener: INFO

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0

