server:
  tomcat:
    threads:
      max: 20
logging:
  level:
    root: info
    web: info
    org.springframework.security: info
    net.ttddyy.dsproxy.listener: info
spring:
  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin
    mode: native
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://postgres:5432/gymcrmDb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gymcrm
eureka:
  client:
    enabled: on
    restclient:
      enabled: on
