server:
  tomcat:
    threads:
      max: 20
logging:
  level:
    root: info
    web: info
    org.springframework.security: info
    net.ttddyy.dsproxy.listener: info
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/gymcrmDb
    username: postgres
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gymcrm
eureka:
  client:
    enabled: on
    restclient:
      enabled: on
