logging:
  level:
    root: INFO
    web: INFO
    net.ttddyy.dsproxy.listener: DEBUG
jwt:
  secret-key: ${JWT_SECRET_KEY}
  lifetime: ${JWT_LIFETIME} # in minutes
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/gymcrmDb
    username: postgres
    password: ${DB_PASSWORD}
eureka:
  client:
    restclient:
      enabled: on
